M48
; DRILL file {KiCad (6.0.8)} date Mon Oct 31 16:39:18 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-31T16:39:18-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X2.0356Y-2.0295
X2.0356Y-2.2205
T2
X2.1549Y-2.0177
X2.1549Y-2.2323
T3
X0.138Y-0.135
X2.092Y-0.135
T0
M30
