M48
; DRILL file {KiCad (6.0.9-0)} date Tuesday, December 27, 2022 at 02:01:06 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-12-27T14:01:06-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X6.7244Y-4.3186
X6.7244Y-4.5096
T2
X6.8437Y-4.3068
X6.8437Y-4.5214
T3
X4.8268Y-2.4241
X6.7808Y-2.4241
T0
M30
